### ISSUE TITLE
It looks weird

### ISSUE THREAD

**Issue by FormalSnake** [irenmax/arcy-gmail#1]
![Capture-2023-04-22-102606](https://user-images.githubusercontent.com/90651091/233775628-f97b2935-6b61-456b-a762-2452c8289ad9.png)

**Comment by irenmax** [comment]
Thanks for pointing that out. I am not using Gmail with multiple apps, so I was not aware of the sidebar. I have made some improvements of the sidebar and header, maybe that makes it less weird for you.
If you have any improvements, feel free to make suggestions or open a PR.

**Comment by FormalSnake** [comment]
Thanks, I will check it out!

**Comment by FormalSnake** [comment]
This looks great! But when hovering over an application it still looks white, and the chat itself should be able to be colored, which I don't think is that hard if you know the color palette.

**Comment by irenmax** [comment]
Yes you are right. Right now the boost is made just for Gmail an no other apps. Maybe I (or someone else) can find the time to style the other apps.

**Comment by irenmax** [comment]
I moved this task to a separate issue with some more context and description (#3).
